### ISSUE TITLE
Reporting/alerting on individual queues

### ISSUE THREAD

**Issue by stevehill1981** [channelgrabber/newrelic-gearman-plugin#1]
Hello team,

We use this plugin to monitor a Gearman instance running on our production servers, but there's one feature that we think is missing that we'd find extremely useful. It may also just be that we're not aware of how to do this, so if we're off track (or if it's something New Relic need to add, rather than yourselves), please tell me and I'll stop bugging you :smile: 

Although the plugin gives us the ability to see the size of each queue, and how many jobs are queued in total, we could really use the ability to know when a specific queue reaches a certain number of jobs. This is because some of our queues contain a lot of jobs, but are very low priority, whereas others are very important and we'd need to know if those jobs weren't being processed correctly.

We've looked into other ways to handle this, but because we're already using New Relic's alerting functionality, it'd be great to do it all from within the plugin itself.

If the functionality doesn't already exist (and can be added within the plugin), and someone could point us in the right direction, we'll be equally happy to contribute this functionality back to the community.

Thanks
Stephen

**Comment by nickpeirson** [comment]
I'm glad the plugin is proving useful.

While it wasn't this exact issue, we found similar limitations with NewRelic's plugin and alerting system. We've actually moved to a combination of [StatsD](https://github.com/etsy/statsd), [Graphite](http://graphite.wikidot.com/) and [Grafana](http://grafana.org/) for monitoring and using this data to drive alerts from [Bosun](https://bosun.org/). This allows for much more flexibility than we had working within the constraints of NewRelic.

That being said, I don't know if things have moved on and I'm happy to help if you think it is possible and want any pointers with the plugin code.
